language: ruby
rvm:
- 2.5.0

install:
  - gem install bundler
  # Install Jekyll and dependencies
  - bundle install
  # checks your resulting site to ensure all links and images exist
  - gem install html-proofer

script:
  - bundle exec jekyll build
  - htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

sudo: true # route your build to the container-based infrastructure for a faster build
